### ISSUE TITLE
Docker Mount: permission denied when running `make e2e-tests`

### ISSUE THREAD

**Issue by TechDufus** [kubewarden/go-policy-template#68] opened 2024-02-09 16:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running the `make e2e-tests`, running the `policy.wasm` docker command fails with the following error:
```
go: cannot determine current directory: stat .: permission denied
```

I believe this is because the mount created for `/src` has permissions that the `tinygo` user cannot access. Is there a simple way to resolve this? 

I've simply tried mounting like this `-v ${PWD}:/src:rw` but that isn't working either.

### Expected Behavior

`make e2e-tests` should work as expected.

### Environment

```markdown
Client: Docker Engine - Community
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 11
  Running: 0
  Paused: 0
  Stopped: 11
 Images: 5
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-92-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.752GiB
 ID: f654cf77-d2f4-4b78-a052-deeae9739938
 Debug Mode: false
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 172.18.0.0/16, Size: 24
```

**Comment by flavio** [comment] 2024-02-14 17:26
I cannot reproduce the issue. These are the steps I've followed:

* Boot Ubuntu 22.04.3 LTS official cloud image
* Update all installed packages
* Install `docker.io` package from the official ubuntu repositories
* Install the following extra packages from the official ubuntu repositories: `make`, `bats`
* Download `kwctl` from our release page, put it under `/usr/local/bin`
* Add my user to the `docker` group
* Enable `docker` service at boot time
* Reboot the system

I then cloned this repository and run the `make e2e-tests` command. Everything worked fine

This is the output from my `docker info` command:

```console
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-1050-kvm
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.778GiB
 Name: ubuntu
 ID: 310d606b-7d9c-4a9d-ac5f-9fed98ca2bbb
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

I see we have a different version of docker installed. Where did you take yours?

**Comment by TechDufus** [comment] 2024-02-14 18:03
I've installed docker via this apt repo: 
```apt
deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable
```

**Comment by flavio** [comment] 2024-02-15 10:18
I picked the same version of docker and enabled the same set of options. I cannot reproduce the issue.

Closing

**Closed by flavio** 2024-02-15 10:18 UTC
